### ISSUE TITLE
get_qr() not working on Linux VM 

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-python#13]
I have created Flask API for my project, It works fine on my windows 10 system. 

For the same project I have created docker file and hosted it on the docker hub and pull it on my local system(i.e. Linux VM) and tried to execute get_qr(), It throw error like this 

>ErrMessage: unknown command: session/7b697eab29671f4c8a1e12ef6ac56174/element/0.4530369317596512-1/screenshot

Is anyone has face same error?

**Comment by mrodal** [comment]
I use it on ubuntu and works fine. are you using firefox or chrome?

**Comment by manojsitapara** [comment]
I am using Chrome

**Comment by mrodal** [comment]
and are you using headless=True?

**Comment by manojsitapara** [comment]
Yes

**Comment by manojsitapara** [comment]
This is my docker file script

FROM joyzoursky/python-chromedriver:3.6-alpine3.7

RUN apk add --no-cache python3-dev \
    && pip3 install --upgrade pip

RUN apk add libmagic

WORKDIR /app

COPY . /app

RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev

RUN apk add build-base python-dev py-pip jpeg-dev zlib-dev
ENV LIBRARY_PATH=/lib:/usr/lib


RUN pip3 --no-cache-dir install -r requirements.txt


EXPOSE 5000

ENTRYPOINT ["python3"]

CMD ["app.py"]

**Comment by manojsitapara** [comment]
Note: this function works fine without any issue.
g.driver.screenshot(image_path)

**Comment by mrodal** [comment]
Could you try `joyzoursky/python-chromedriver:3.6` instead of `joyzoursky/python-chromedriver:3.6-alpine3.7` ?

**Comment by manojsitapara** [comment]
This doesn't help :(

>Could you try joyzoursky/python-chromedriver:3.6 instead of joyzoursky/python-chromedriver:3.6-alpine3.7 ?

**Comment by manojsitapara** [comment]
I have found that this issue was only with chrome, with firefox it works fine.

Here is sample docker file if anyone will face same issue.

FROM python:alpine3.9
RUN apk update

RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-2.30-r0.apk
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-bin-2.30-r0.apk
RUN apk add glibc-2.30-r0.apk
RUN apk add glibc-bin-2.30-r0.apk


RUN apk add firefox-esr=60.9.0-r0


RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
RUN tar -zxf geckodriver-v0.26.0-linux64.tar.gz -C /usr/local/bin
RUN geckodriver --version


RUN apk add --no-cache python3-dev \
    && pip3 install --upgrade pip

RUN apk add libmagic

WORKDIR /app

COPY . /app

RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev

RUN apk add build-base python-dev py-pip jpeg-dev zlib-dev
ENV LIBRARY_PATH=/lib:/usr/lib


RUN pip3 --no-cache-dir install -r requirements.txt


EXPOSE 5000

ENTRYPOINT ["python3"]

CMD ["app.py"]

**Comment by mrodal** [comment]
Excellent! thanks for sharing the solution
