### ISSUE TITLE
No module named 'axolotl'

### ISSUE THREAD

**Issue by lordmurda** [open-wa/wa-automate-python#14]
File "D:\****\ src \ __init__.py", line 20, in <module>
    from axolotl.kdf.hkdfv3 import HKDFv3
ModuleNotFoundError: No module named 'axolotl'

**Comment by mrodal** [comment]
Please check this https://github.com/open-wa/wa-automate-python/issues/3

**Comment by joselmy-diaz** [comment]
pip install python-axolotl
