### ISSUE TITLE
Different output from firefox and chrome browser

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-python#16]
Firefox and Chrome browser returns different json object from same function.

for example: group_get_participants_ids() API return following output 

From FireFox:
```
[
    {
        "_serialized": "XXXXXXXXXXX@c.us",
        "server": "c.us",
        "user": "XXXXXXXXXXX"
    },
    {
        "_serialized": "XXXXXXXXXXX@c.us",
        "server": "c.us",
        "user": "XXXXXXXXXXX"
    },
    {
        "_serialized": "XXXXXXXXXXX@c.us",
        "server": "c.us",
        "user": "XXXXXXXXXXX"
    }
]
```

From Chrome:

```
[
     "XXXXXXXXXXX@c.us",
     "XXXXXXXXXXX@c.us",
     "XXXXXXXXXXX@c.us",
     "XXXXXXXXXXX@c.us"
 ]
```

Is there any reason? Because of this project will be tightly couple. :(

**Comment by mrodal** [comment]
Please try the latest version 1.1.5 that has this fixed, and if you find more cases like this one report them

Thanks!

**Comment by manojsitapara** [comment]
@mrodal from where I can download v1.1.5? I do not see any latest check in?

**Comment by mrodal** [comment]
Upgrade with
pip install --upgrade openwa

**Comment by manojsitapara** [comment]
Thanks !! I got the latest version but it looks like it is breaking existing functionality for example look at below error
`'WhatsAPIDriver' object has no attribute 'get_all_groups'`

I think this get_all_groups functionality was added in the version 1.1.2 [https://github.com/open-wa/wa-automate-python/issues/11](Issue#11)

Can you please take a look? Thank you !!

**Comment by mrodal** [comment]
Oh, Im very sorry, the pc where I had those changes died and I though I had pushed those commits, but looks like not.. I'm waiting for a motherboard to replace it and then I'll have access to that again.. 

In the meantime I'll try to recover that from the published 1.1.2 version

**Comment by mrodal** [comment]
Done, please use version 1.1.6

**Comment by manojsitapara** [comment]
No problem !! I understand it happen, Thank you for your quick fix !!

I have checked the new fix on both Chrome and FireFox, Both gives identical results now.

Thanks you !!
