### ISSUE TITLE
Can you create a conversation from a number that I do not have registered as a contact?

### ISSUE THREAD

**Issue by 3dluis** [open-wa/wa-automate-python#19]
Can you create a conversation from a number that I do not have registered as a contact?

I have made a test from whatsapp web and it is possible to do it.

window.WAPI.sendMessage = function (id, message, done) {
    var chat = WAPI.getChat(id);

    if (chat === undefined){
        let userId = new window.Store.UserConstructor(id, {intentionallyUsePrivateConstructor: true});
        chat = WAPI.getChat(userId);
    }

**Comment by mrodal** [comment]
Hey, @3dluis for that feature a license key is required. Check point 2 [here](https://github.com/open-wa/wa-automate-python#starting-a-conversation)

This decision was made to mitigate the risk of noobs spamming and misusing the application, as well as to support maintainers. When requesting a license key, the user has to specify the reason that he needs it, this way we can keep some kind of control over this feature and avoid misuse to some extent.
