### ISSUE TITLE
Can't get profile pictures of users.

### ISSUE THREAD

**Issue by WolfDWyc** [open-wa/wa-automate-python#22]
Getting profile pictures of other people always returns None.
The error seems to be in contact.py and wapi.js
```python
        if 'profilePicThumbObj' in js_obj:
            self.profile_pic = js_obj["img"].get('eurl', None)
```
the obj is always {}, because of:
```javascript
    profilePicThumbObj: obj.profilePicThumb ? WAPI._serializeProfilePicThumb(obj.profilePicThumb) : {},
```

**Comment by mrodal** [comment]
Hi, what do you mean other people?

**Comment by WolfDWyc** [comment]
> Hi, what do you mean other people?

For example, these are all None, except my own picture.
```python
                    partic_list = driver.get_chat_from_id(message.chat_id).get_participants()
                   
                    for user in partic_list:
                        print(user.profile_pic)
```

**Comment by mrodal** [comment]
try the new version 1.2.0.
You can upgrade running:
`pip install --upgrade openwa`

**Comment by WolfDWyc** [comment]
> try the new version 1.2.0.
> You can upgrade running:
> `pip install --upgrade openwa`

I just did, still got the same result.
