### ISSUE TITLE
How to start a new chat with contact

### ISSUE THREAD

**Issue by undrgrad** [open-wa/wa-automate-python#23]
> - Advertising of monetized Frameworks is strictly forbidden and will be reported 
> - [ ] The language must be English, if you are not fluent in English consider using: https://www.deepl.com/translator if it supports your native language
> 
> - [ ] Please check if any other issue already adresses your concerns or if a recent PR is already fixing the mentioned issue
> 
> - [ ] Please make sure to **format your code**, and to mark your code as such, with the provided tools from github (upper right of this box)
> 
> - [ ] Please state your **Operating System (inlcuding version)**, your **Python Version**, and your **installation way (pip, from repo)** and if you are running it inside a docker container
> 
> - [ ] Note that the pip installation might be behind, so try to fix your issue with a pull from the repo and update to the most recent version
> 
> - [ ] Follow the Stackoverflow Guidelines (https://stackoverflow.com/help/how-to-ask) when in need of help
>
> - [ ] Consider posting your question on Stackoverflow if it is a general programming question
> 
> - [ ] There will be no support for spamming, or other mischief 
> 
>- [ ] There will be no support for finding professionals

**Comment by darkash** [comment]
https://github.com/open-wa/wa-automate-python#get-chat-by-number
isn't it already as documented in readme?

**Comment by mrodal** [comment]
exactly, thanks @darkash
