### ISSUE TITLE
after scan qr, now client is_alive become false

### ISSUE THREAD

**Issue by irvanrahadhian** [open-wa/wa-automate-python#24]
Hello, first of all thank you for this amazing lib, im using it for several days and its working fine.
im using it with flask, but now i cant seems to make it work again after scan qr

**Comment by mrodal** [comment]
Hey! Im happy to hear that you like it!
Could you provide your whatsapp web version?

You can see it in wp web settings->help
![image](https://user-images.githubusercontent.com/20667544/83816781-90eed600-a699-11ea-998a-033673463eb8.png)

**Comment by irvanrahadhian** [comment]
im using headless option in ubuntu, is there any way to check it?

**Comment by mrodal** [comment]
log in on a normal browser window on your pc to get the version

**Comment by irvanrahadhian** [comment]
on my local computer is Version 2.2021.4

**Comment by mrodal** [comment]
Please try the new version 1.2.1 and let me know if it works. A new WP web version came out recently that broke the bot

**Comment by irvanrahadhian** [comment]
oke i'll try to update the package.

**Comment by irvanrahadhian** [comment]
it said i already have the latest package openwa 1.2.0
![Screen Shot 2020-06-05 at 06 21 56](https://user-images.githubusercontent.com/24669933/83819778-fcb25c80-a6f4-11ea-90fc-210c197d0f61.png)

where to download 1.2.1 ?

**Comment by mrodal** [comment]
try with pip install --upgrade openwa

**Comment by irvanrahadhian** [comment]
> try with pip install --upgrade openwa

yes i already done it with pip install -U openwa, and still got the 1.2.0

**Comment by irvanrahadhian** [comment]
WOW youre the best @mrodal , thank you so much. i really love it because it much faster than the other, Thanks

**Comment by mrodal** [comment]
Great!
