### ISSUE TITLE
Discord group for WebWhatsAPI

### ISSUE THREAD

**Issue by RasphostUser** [open-wa/wa-automate-python#26]
hello, i created discord group for abandoned webwhatsapi, then i found yours, i really want to keep this project stay alive, link to join https://discord(,)gg/n4nW8dZ (IT IS NOT AD)

**Comment by mrodal** [comment]
why dont you join the new discord group? it has many more people on it

**Comment by RasphostUser** [comment]
wdym with "new"?

**Comment by RasphostUser** [comment]
2 times more people is not "many more"

**Comment by mrodal** [comment]
190 people is many more than 11 to me

This is the group, just in case you are looking at a different one https://discord.gg/fKXGA4

**Comment by irvanrahadhian** [comment]
hello @mrodal , i tried the discord link, but it already expire, can i join the group too?
