### ISSUE TITLE
I suggest sending d a WhatsApp link which starts a message with A

### ISSUE THREAD

**Issue by 3cubos** [open-wa/wa-automate-python#27]
https://github.com/open-wa/wa-automate-nodejs/blob/master/README.md#starting-a-conversation

Do i need the key? what the value? $$$
For 1 phone?

**Comment by mrodal** [comment]
What's your requirement? You need a license to contact new numbers, that means numbers that you don't have a conversation with. 

You can see the pricing here: https://gumroad.com/a/825717875

For the key you need to select at least the second tier

**Comment by 3cubos** [comment]
> What's your requirement? You need a license to contact new numbers, that means numbers that you don't have a conversation with.
> 
> You can see the pricing here: https://gumroad.com/a/825717875
> 
> For the key you need to select at least the second tier

my situation:

Hi, I'm doing some tests. Using the example: new_messages_observer.py. The problem is when I send a message from a new number, I don't read a new message from the new number. How to fix this?
ex:
my phone = A, sister = b, mom = c, father = d
b -> sender text -> A OK
c -> sender text -> A OK
d -> sender text -> A NOT receive, is not in the phone's contact list.
How to fix this?
Sorry my bad English, from Brazil.

**Comment by irvanrahadhian** [comment]
> > What's your requirement? You need a license to contact new numbers, that means numbers that you don't have a conversation with.
> > You can see the pricing here: https://gumroad.com/a/825717875
> > For the key you need to select at least the second tier
> 
> my situation:
> 
> Hi, I'm doing some tests. Using the example: new_messages_observer.py. The problem is when I send a message from a new number, I don't read a new message from the new number. How to fix this?
> ex:
> my phone = A, sister = b, mom = c, father = d
> b -> sender text -> A OK
> c -> sender text -> A OK
> d -> sender text -> A NOT receive, is not in the phone's contact list.
> How to fix this?
> Sorry my bad English, from Brazil.

hello i assume you cant get new message from new user that has no chat room / conversation before.
you can see the solution in here #25

**Comment by darkash** [comment]
> > What's your requirement? You need a license to contact new numbers, that means numbers that you don't have a conversation with.
> > You can see the pricing here: https://gumroad.com/a/825717875
> > For the key you need to select at least the second tier
> 
> my situation:
> 
> Hi, I'm doing some tests. Using the example: new_messages_observer.py. The problem is when I send a message from a new number, I don't read a new message from the new number. How to fix this?
> ex:
> my phone = A, sister = b, mom = c, father = d
> b -> sender text -> A OK
> c -> sender text -> A OK
> d -> sender text -> A NOT receive, is not in the phone's contact list.
> How to fix this?
> Sorry my bad English, from Brazil.

do you mean A as sender or A as the receiver
if A as sender then yes you will require license for that
if A as receiver the you won't need license and message_observer scenario should suffice even if the B, C or D is not in your contact list or never chat to you

**Comment by irvanrahadhian** [comment]
> > > What's your requirement? You need a license to contact new numbers, that means numbers that you don't have a conversation with.
> > > You can see the pricing here: https://gumroad.com/a/825717875
> > > For the key you need to select at least the second tier
> > 
> > 
> > my situation:
> > Hi, I'm doing some tests. Using the example: new_messages_observer.py. The problem is when I send a message from a new number, I don't read a new message from the new number. How to fix this?
> > ex:
> > my phone = A, sister = b, mom = c, father = d
> > b -> sender text -> A OK
> > c -> sender text -> A OK
> > d -> sender text -> A NOT receive, is not in the phone's contact list.
> > How to fix this?
> > Sorry my bad English, from Brazil.
> 
> do you mean A as sender or A as the receiver
> if A as sender then yes you will require license for that
> if A as receiver the you won't need license and message_observer scenario should suffice even if the B, C or D is not in your contact list or never chat to you

No, what he meant was he cannot receive new message from user if the user never been / have a chat room with the receiver.

but it already fixed in version 1.3.0

**Comment by irvanrahadhian** [comment]
i think this issue can be close @mrodal ? :)

**Comment by mrodal** [comment]
great!
