### ISSUE TITLE
pip install -r requirements.txt python-axolotl error

### ISSUE THREAD

**Issue by mhndm** [open-wa/wa-automate-python#3]
ubuntu 16.04
pyhton 3.7

the error :

Collecting python-axolotl-curve25519>=0.4.1
  Using cached python-axolotl-curve25519-0.4.1.post2.tar.gz (79 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hnesldo7/python-axolotl-curve25519/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hnesldo7/python-axolotl-curve25519/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-hnesldo7/python-axolotl-curve25519/pip-egg-info
         cwd: /tmp/pip-install-hnesldo7/python-axolotl-curve25519/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/usr/local/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mrodal** [comment]
can you provide a little more info? how exactly are you installing open-wa and when are you getting the error?

**Comment by mhndm** [comment]
i clone the code and then: pip install -r requirements.txt

**Comment by mrodal** [comment]
Ok, did you check the issue I linked above? looks like some library missing on your system (libffi-dev)

**Comment by mhndm** [comment]
its installed

**Comment by mhndm** [comment]
the problem soved by :

sudo apt-get install build-essential checkinstall

sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev \
    libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev

thanks @mrodal for ure interest :+1:

**Comment by mrodal** [comment]
Great! Thanks for posting the solution!

**Comment by diegofrias** [comment]
> Great! Thanks for posting the solution!

Hi, anybody could help me by saying how can I solve this problem in windows 10 without sudo apt-get  ...?
