### ISSUE TITLE
Unable to send WhatsApp message to unsaved even with a license key.

### ISSUE THREAD

**Issue by ManjitPardeshi** [open-wa/wa-automate-python#37]
Hello @smashah and @mrodal,
Yesterday I had purchased a license key and then I passed it as license_key argument but it is still not sending to unsaved chats.
It is directly returning True. 
I am using Chrome Browser. Please help me as soon as possible.

**Comment by mrodal** [comment]
could you talk to me on discord? to solve it asap. I'm @ladorm on discord
