### ISSUE TITLE
WebDriver consuming lot of memory and CPU

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-python#38]
I am trying to run whatsapp for more than 50 users, but for each user wa-automate-python create new instance, which is correct, but due to this it consume huge memory and CPU usage.

Is there any way to reduce the memory and CPU usage? I have tried to follow the instruction for Firefox to reduce memory and CPU usage, but it doesn't help.

I know this may not relevant question to wa-automate-python, but this to see if anyone has any good idea to handle such scenario.

**Comment by mrodal** [comment]
sorry, I'm closing the issue because its not related to this repo. 50 is much more instances than I've ever used, maybe on discord you can get some help!
