### ISSUE TITLE
subscribe_acks confusion

### ISSUE THREAD

**Issue by darkash** [open-wa/wa-automate-python#4]
subscribe_acks method check for 'on_ack_received', but in this line it calls different method that's not being checked on subscribe_acks. Shouldn't it probably call 'on_ack_received' instead?

https://github.com/open-wa/wa-automate-python/blob/c18a825ac65d1ddad49a8f52fe02743db4280567/src/wapi_js_wrapper.py#L256

Note that I haven't read the whole codebase yet

**Comment by mrodal** [comment]
You are right, good catch!
Its fixed now
