### ISSUE TITLE
send_message_with_auto_preview() return always False value

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-python#40]
Following method always return False even it send message to the participant

`send_message_with_auto_preview(chat_id=chat_id, url=url, text=text)`

Note: send_message() method return True and False correctly.

`chat_send_message(chat_id=chat_id, message=text)`

Earlier send_message_with_auto_preview() was working fine but after update wa-automate-python it give this issue

Can you please help me?

**Comment by mrodal** [comment]
Its being fixed, it should be ready for tonight

**Comment by manojsitapara** [comment]
@mrodal is new build ready?

**Comment by mrodal** [comment]
sorry, not yet, we are waiting for a fix on the parent nodejs repo

**Comment by mrodal** [comment]
if you need it fixed now, you can copy this
```javascript
window.WAPI.sendLinkWithAutoPreview = async function (chatId, url, text) {
    text = text || '';
    var chatSend = WAPI.getChat(chatId);
    if (chatSend === undefined) {
        return false;
    }
    const linkPreview = await Store.WapQuery.queryLinkPreview(url);
    return (await chatSend.sendMessage(text.includes(url) ? text : `${url}\n${text}`, {linkPreview}))=='OK'
}
```

at the end of src/js/pywapi.js

**Comment by manojsitapara** [comment]
No problem, I will wait till new build ready. By the way above fix is working.

**Comment by manojsitapara** [comment]
It's working. Thank you !!
