### ISSUE TITLE
Unable to open chrome instance with --headless and --user-data-dir flag at the same time. 

### ISSUE THREAD

**Issue by ManjitPardeshi** [open-wa/wa-automate-python#41]
@mrodal  I have been trying to open  a WhatsApp web instance with `headless=True` and `profile='blah..blah...blah' ` but the instance is not starting and it is stuck and also not showing any thing on the screen... But when i try with `headless= False` the instance works perfect...
Please help me fix the issue...

**Comment by darkash** [comment]
what do you mean stuck and not showing anything on the screen?
isn't that what headless option is for?

or what you mean the `wait_for_qr()` method is stuck and later crash? If that's the case, you can try bisect the selenium lib and put log in there to find what's going on. or check the browser debug log
