### ISSUE TITLE
Unable to add participant in existing group

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-python#47]
I am getting following error while adding participant in existing group

> raise JsException(
openwa.wapi_js_wrapper.JsException: Error in function addParticipant ([object Object]). Command: return WAPI.pyFunc(()=>WAPI.addParticipant('123456789@g.us','755775775@c.us'), arguments[0])

here is my code
`res = g.driver.add_participant_group(idParticipant=group_member_id, idGroup=group_id)`

Can anyone please help me?

**Comment by mrodal** [comment]
Its working fine for me, can you try executing `WAPI.addParticipant('123456789@g.us','755775775@c.us')`  on the browser's console directly?

**Comment by manojsitapara** [comment]
I the command as you mentioned above, got this error

> Uncaught SyntaxError: unexpected token: identifier

**Comment by darkash** [comment]
the first number is a group (?)
note that it's `@g.us` instead of `@c.us`

otherwise you can ignore my comment, it's also working fine on my end

**Comment by manojsitapara** [comment]
ohhh what a silly mistake I did. I was trying to add participant in the group in which I was not admin. I am sorry for the trouble for everyone.
