### ISSUE TITLE
Sending Media is not working

### ISSUE THREAD

**Issue by GauthamramRavichandran** [open-wa/wa-automate-python#49]
Operating System : Ubuntu 18.04.4 LTS
Python : Python 3.6.9
Installation : via pip

```
dver = WhatsAPIDriver(headless = True)
dver.set_local_storage(loads(payload))
dver.driver.refresh()
sleep(20)
if dver.is_logged_in():
	for grp in dver.get_all_groups():
		print(grp.id, grp.name)
		dver.chat_send_message(chat_id = grp.id, message = "Hi! Test #3")
		grp.send_media(image_path = '/home/xxxxxx/some_image.png', caption = "Test 3")
else:
	print("Not logged In")
```
The `send_message` is working, was able to send the text message in the groups. But `send_media` is not working, it's throwing any error/ anything in logs as well. 

**Output:**
Shows the grp.id grp.name of all groups and sends text message alone

**Comment by GauthamramRavichandran** [comment]
I have tried the following,

- Sending .jpg files
- Giving a relative path
- Tried `wapi_functions.sendImage` with base64 of the image

**Comment by marcelocecin** [comment]
use https://github.com/mukulhase/WebWhatsapp-Wrapper

**Comment by GauthamramRavichandran** [comment]
This repo is discontinued, then?
I'll use that pip package.

**Comment by mrodal** [comment]
Its weird, I just tried and it is working correctly doing `group.send_media(IMAGE_PATH, 'test')` sending a png or jpg.
What does grp.send_media return for you?
This repo is not discontinued

**Comment by mrodal** [comment]
I just fixed an issue, can you try with the latest version? 1.3.10

**Comment by GauthamramRavichandran** [comment]
Great!, It's fixed now, why was it not working earlier? I had not received any errors as well in the python script, it seems there's a catch section in the js but could it be re-raised to python, for handling at python side
