### ISSUE TITLE
no mudule named src

### ISSUE THREAD

**Issue by mchoud** [open-wa/wa-automate-python#53]
Hi Brother

I have already tried to install, when step is  running this command,

docker run --network selenium -it -e SELENIUM='http://firefox:4444/wd/hub' -v $(pwd):/app  wa-automate-python /bin/bash -c "pip install ./;pip list;python sample/remote.py"

there is an error msg

 File "sample/remote.py", line 2, in <module>
    from src import WhatsAPIDriver
ModuleNotFoundError: No module named 'src'

I run the command from within wa-automate-python folder.

What is going wrong with me

Thank you so much for your help

**Comment by mrodal** [comment]
Try this
docker run --network selenium -it -e SELENIUM='http://firefox:4444/wd/hub' -v $(pwd):/app wa-automate-python /bin/bash -c "pip install ./;export PYTHONPATH=`pwd`;pip list;python sample/remote.py"
