### ISSUE TITLE
send_message_with_auto_preview() API is not working

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-python#55]
This API was working with earlier version but it is not working now, I am getting following error

> raise JsException("Error in function {0} ({1}). Command: {2}".format(self.function_name, e.msg, command))

> openwa.wapi_js_wrapper.JsException: Error in function sendLinkWithAutoPreview (Timed out after 60000 ms). Command: return WAPI.pyFunc(()=>WAPI.sendLinkWithAutoPreview(

Can you please help me to resolve this issue?

Please note: g.driver.chat_send_message() API is working fine without any issue.

**Comment by mrodal** [comment]
It is working for me.. the error said timeout, maybe it was a network problem or the url you were trying to pass timed out?

**Comment by manojsitapara** [comment]
@mrodal Link send_message_with_auto_preview() API return true value till openwa==1.3.8, but not in later version it always return False value and not posting messages in WhatsApp groups or single contact. 

Can you please check from your end if it is working for openwa==1.3.10?

here is my code

` chat_id = "1234567890@c.us"`
`    url = "https://amzn.to/35kq8hQ"`
`    text = "Hello World"`
`    res = g.driver.send_message_with_auto_preview(chat_id=chat_id, url=url, text=text)`

> `res` value is always False in latest version.

**Comment by mrodal** [comment]
Please follow this new issue that is the cause of the error you reported:
https://github.com/open-wa/wa-automate-nodejs/issues/1118

**Comment by smashah** [comment]
@manojsitapara I'm also trying with your link (one plus 7t glacier blue etc..)  and it is working ok for me. Are you editing wapi.js?

**Comment by manojsitapara** [comment]
@smashah No I have not edited wapi.js, it is same file which get downloaded from pip.

**Comment by smashah** [comment]
@manojsitapara can yo restart your session and try again please

**Comment by manojsitapara** [comment]
@smashah I did that but same issue.
