### ISSUE TITLE
Error while executing docker command

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-python#57]
I am getting following error while running following docker command 

`docker run --network selenium -it -e SELENIUM='http://firefox:4444/wd/hub' -v "%cd%:/app" wa-automate-python /bin/bash -c "pip install ./;pip list;python sample/remote.py"
`

> Traceback (most recent call last):
>   File "sample/remote.py", line 2, in <module>
>     from src import WhatsAPIDriver
> ModuleNotFoundError: No module named 'src'
> 

Am I missing something?

**Comment by mrodal** [comment]
this is more of a python problem, take a look at this https://github.com/open-wa/wa-automate-python/issues/53
