### ISSUE TITLE
TypeError in sendMessage

### ISSUE THREAD

**Issue by GauthamramRavichandran** [open-wa/wa-automate-python#58]
Installed via pip
Ubuntu 20.04 LTS
openwa 1.3.10
Python 3.8.5

`sendMessage` was working fine till yesterday, now it's throwing this error always

**Code**:
`driver.chat_send_message(chat_id = '99999999-11111111111@g.us', message = 'How you doing @here\r\n\r\nhttps://random-link-here.in')`

**Error:**
`Error in function sendMessage (TypeError: _0x413fc2 is undefined). Command: return WAPI.pyFunc(()=>WAPI.sendMessage('99999999-11111111111@g.us','How you doing @here\r\n\r\nhttps://random-link-here.in'), arguments[0])`

**Comment by mrodal** [comment]
I just tried it and it's working fine for me on chrome. 
What browser version are you using?

**Comment by GauthamramRavichandran** [comment]
Firefox 81

**Comment by mrodal** [comment]
Tested and working on firefox 81 too. 
Maybe it was a temporary error, because the lib uses an external js that could have had an issue temporarily. Do you still get the same error?

**Comment by GauthamramRavichandran** [comment]
It's working now, but sometimes it throws that error. Is there any reason it's happening? How to resolve if occurs again?

**Comment by mrodal** [comment]
Im closing this, if you get the error again please open new issue
