### ISSUE TITLE
raise WebDriverException( selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

### ISSUE THREAD

**Issue by R3N4L** [open-wa/wa-automate-python#60]
Traceback (most recent call last):                                     File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'
root@ip-172-31-30-183:~# python3 app.py                              Traceback (most recent call last):                                     File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 72, in start                                       self.process = subprocess.Popen(cmd, env=self.env,                 File "/usr/lib/python3.8/subprocess.py", line 854, in __init__         self._execute_child(args, executable, preexec_fn, close_fds,       File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child                                                                       raise child_exception_type(errno_num, err_msg, err_filename)     FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'                                                                     During handling of the above exception, another exception occurred:                                                                       Traceback (most recent call last):                                     File "app.py", line 3, in <module>                                     driver = WhatsAPIDriver()                                          File "/usr/local/lib/python3.8/dist-packages/openwa/__init__.py", line 194, in __init__                                                     self.driver = webdriver.Firefox(capabilities=capabilities, options=options,                                                             File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__                                self.service.start()                                               File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 81, in start                                       raise WebDriverException(                                        selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by mrodal** [comment]
you need the geckodriver executable in the PATH variable.
