### ISSUE TITLE
Some Reverse-Engineering and Youtube preview

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-python#62]
Hi there :) first of all thanks alot for a great repo

was wondering if you can shed any light on how to get the list of all possible functions from the js store

for example, I would like to send a message with a Youtube Preview - The one that is able to play straight from the chat
if anyone knows how to do this (yt preview) please share it will be very appreciated

and if you can point me in the right direction on how to start reverse engineering the wap js store it will be great
Thank you so much and have a good one :) :+1:

**Comment by mrodal** [comment]
Hi, you can start looking here https://github.com/open-wa/wa-automate-nodejs/blob/master/src/lib/wapi.js how the functions are extracted. You can also ask in that repo or in the [discord server](https://discord.gg/dnpp72a) where there are more people working on the js part

Regards
