### ISSUE TITLE
Media Message Url is null  (client_url)

### ISSUE THREAD

**Issue by 3dluis** [open-wa/wa-automate-python#63]
When the audio format seems to have changed, the js_object client_url not found.

{
"accuracy":"None",
"ack":0,
"appStateSyncKeyRequest":"None",
"appStateSyncKeyShare":"None",
"author":"None",
"backgroundColor":"None",
"bizPrivacyStatus":"None",
"body":"None",
"broadcast":false,
"broadcastId":"None",
"broadcastParticipants":"None",
"businessOwnerJid":"None",
"buttons":"None",
"buttonsResponse":"None",
"canonicalUrl":"None",
"caption":"None",
"chat":{
"archive":false,
"changeNumberNewJid":"None",
"changeNumberOldJid":"None",
"contact":{
"actualActors":"None",
"formattedName":"+XDFDSFSFDSF",
"hostStorage":"None",
"id":{
"_serialized":"XXDDDDDD@c.us",
"server":"c.us",
"user":"XXXXXX"
},
"isBusiness":false,
"isEnterprise":false,
"isHighLevelVerified":"None",
"isMe":false,
"isMyContact":false,
"isPSA":false,
"isUser":true,
"isVerified":"None",
"isWAContact":true,
"labels":[

     ],
     "msgs":"None",
     "name":"None",
     "privacyModeTs":"None",
     "profilePicThumbObj":{
        
     },
     "pushname":"Luis Diaz",
     "sectionHeader":"None",
     "shortName":"None",
     "statusMute":false,
     "type":"in",
     "verifiedLevel":"None",
     "verifiedName":"None"
  },
  "ephemeralDuration":0,
  "ephemeralSettingTimestamp":0,
  "groupMetadata":"None",
  "id":{
     "_serialized":"XXDDDDDD2@c.us",
     "server":"c.us",
     "user":"XXXXXXXDDDSD"
  },
  "isAnnounceGrpRestrict":"None",
  "isGroup":false,
  "isReadOnly":false,
  "kind":"chat",
  "labels":"None",
  "lastReceivedKey":{
     "_serialized":"true_XXDDSD@c.us_3EB01761D2AFFFDFDSFSFD69E2AD",
     "fromMe":true,
     "id":"3EB01761D2AFFD69E2AD",
     "remote":{
        "_serialized":"FGFGFXXXX@c.us",
        "server":"c.us",
        "user":"FGFGFGCCC"
     }
  },
  "modifyTag":"None",
  "msgUnsyncedButtonReplyMsgs":"None",
  "msgs":"None",
  "muteExpiration":0,
  "name":"None",
  "notSpam":true,
  "pendingMsgs":false,
  "pin":0,
  "presence":{
     "chatstates":[
        
     ],
     "id":{
        "_serialized":"GFFGFGFG@c.us",
        "server":"c.us",
        "user":"YGFFGFGFG"
     }
  },
  "t":1612829661,
  "unreadCount":0
},
"chatId":{
"_serialized":"XXDDFDDSDSDS@c.us",
"server":"c.us",
"user":"454asa78"
},
"clearMedia":"None",
"clientUrl":"None",
"comment":"None",
"content":"None",
"ctwaContext":"None",
"currencyCode":"None",
"degrees":"None",
"deprecatedMms3Url":"https://mmg.whatsapp.net/d/f/AlRmME5Qlgfdgdgd46THraKOWsz7fY7676ZVlIcVXCI4bDgq_n_Vm0uE.enc",
"description":"None",
"devicesAdded":"None",
"devicesRemoved":"None",
"directPath":"/v/t62.7117-24/24328292_36739fg5472782719092_9005158939608816835_n.enc?oh=803f19cf6c746b98a6f41558fb914a40&oe=604D44EB",
"doNotPlayInline":"None",
"duration":"2",
"dynamicReplyButtons":"None",
"encFilehash":"Xx1UykOFsl4IEfbd84B5zD1mmj+UJmj+c878DW5Nans=",
"ephemeralDuration":"None",
"ephemeralOutOfSync":"None",
"ephemeralSettingTimestamp":"None",
"ephemeralSharedSecret":"None",
"ephemeralStartTimestamp":"None",
"filehash":"bb1nRQ5KN454eey4xMxc2WWru5aTpjw8t+hAKaBl8ezGaKe8=",
"filename":"None",
"finalAccuracy":"None",
"finalDegrees":"None",
"finalLat":"None",
"finalLng":"None",
"finalSpeed":"None",
"finalThumbnail":"None",
"finalTimeOffset":"None",
"firstFrameLength":"None",
"firstFrameSidecar":"None",
"font":"None",
"footer":"None",
"forwardingScore":"None",
"from":{
"_serialized":"xxxxcc@c.us",
"server":"c.us",
"user":"XXX"
},
"gifAttribution":"None",
"height":"None",
"historySyncMetaData":"None",
"hydratedButtons":"None",
"id":"false_XXXXDS@c.us_3A4DTE4836C81402D8E7848",
"interactiveAnnotations":"None",
"invis":false,
"inviteCode":"None",
"inviteCodeExp":"None",
"inviteGrp":"None",
"inviteGrpJpegThum":"None",
"inviteGrpName":"None",
"isAnimated":"None",
"isDynamicReplyButtonsMsg":false,
"isForwarded":false,
"isFromTemplate":false,
"isGif":"None",
"isGroupMsg":false,
"isLink":"None",
"isLive":"None",
"isMMS":"None",
"isMedia":false,
"isNewMsg":true,
"isNotification":false,
"isPSA":false,
"isThisDeviceAdded":"None",
"isVcardOverMmsDocument":false,
"isViewOnce":"None",
"itemCount":"None",
"labels":[

],
"lat":"None",
"list":"None",
"listResponse":"None",
"lng":"None",
"loc":"None",
"matchedText":"None",
"mdDowngrade":"None",
"mediaData":{
"_listeningToSwSupport":false,
"_swStreamingSupported":false,
"animatedAsNewMsg":false,
"animationDuration":0,
"aspectRatio":"None",
"directPath":"None",
"documentPreview":"None",
"duration":"None",
"durationFloat":"None",
"emojis":"None",
"encFilehash":"None",
"filehash":"None",
"filename":"None",
"firstFrameLength":"None",
"firstFrameSidecar":"None",
"fullHeight":"None",
"fullPreviewData":"None",
"fullPreviewSize":"None",
"fullWidth":"None",
"gifAttribution":"None",
"isAnimated":"None",
"isGif":"None",
"isVcardOverMmsDocument":false,
"isViewOnce":false,
"mediaBlob":"None",
"mediaKey":"None",
"mediaKeyTimestamp":"None",
"mediaStage":"INIT",
"mimetype":"None",
"pageCount":"None",
"parsedVcards":"None",
"preview":"None",
"progressiveStage":"None",
"renderableUrl":"None",
"rgbaBuffer":"None",
"rgbaHeight":"None",
"rgbaWidth":"None",
"sidecar":"None",
"singleLoopDuration":"None",
"size":"None",
"subtype":"None",
"type":"unknown"
},
"mediaKey":"qpRZeN8ZljxKU/krhGHGJuZggf7ARKEqwaALGg2Er1werM=",
"mediaKeyTimestamp":1617782829673,
"mentionedJidList":[

],
"message":"None",
"mimetype":"audio/ogg; codecs=opus",
"multicast":"None",
"notifyName":"",
"orderId":"None",
"orderTitle":"None",
"pageCount":"None",
"paymentAmount1000":"None",
"paymentCurrency":"None",
"paymentExpiryTimestamp":"None",
"paymentMessageReceiverJid":"None",
"paymentNoteMsg":"None",
"paymentRequestMessageKey":"None",
"paymentStatus":"None",
"paymentTransactionTimestamp":"None",
"priceAmount1000":"None",
"productId":"None",
"productImageCount":"None",
"protocolMessageKey":"None",
"quotedMsg":"None",
"quotedMsgObj":"None",
"quotedParticipant":"None",
"quotedRemoteJid":"None",
"quotedStanzaID":"None",
"recipients":"None",
"recvFresh":true,
"retailerId":"None",
"richPreviewType":"None",
"scanLengths":"None",
"scansSidecar":"None",
"selectedId":"None",
"selectedIndex":"None",
"self":"in",
"sellerJid":"None",
"sender":{
"actualActors":"None",
"formattedName":"+CCCXXXXXXX",
"hostStorage":"None",
"id":{
"_serialized":"FFGGGHHH@c.us",
"server":"c.us",
"user":"FFFGFRRTR"
},
"isBusiness":false,
"isEnterprise":false,
"isHighLevelVerified":"None",
"isMe":false,
"isMyContact":false,
"isPSA":false,
"isUser":true,
"isVerified":"None",
"isWAContact":true,
"labels":[

  ],
  "msgs":"None",
  "name":"None",
  "privacyModeTs":"None",
  "profilePicThumbObj":{
     
  },
  "pushname":"pRUEBA",
  "sectionHeader":"None",
  "shortName":"None",
  "statusMute":false,
  "type":"in",
  "verifiedLevel":"None",
  "verifiedName":"None"
},
"sequence":"None",
"shareDuration":"None",
"size":7025,
"speed":"None",
"star":false,
"status":"None",
"streamable":"None",
"streamingSidecar":"None",
"subtype":"None",
"surface":"None",
"t":1612829677,
"templateParams":"None",
"textColor":"None",
"thumbnail":"None",
"thumbnailDirectPath":"None",
"thumbnailEncSha256":"None",
"thumbnailHeight":"None",
"thumbnailSha256":"None",
"thumbnailWidth":"None",
"timestamp":161282FF66559677,
"title":"None",
"to":{
"_serialized":"XXXXXXX@c.us",
"server":"c.us",
"user":"XXXXX"
},
"token":"None",
"totalAmount1000":"None",
"totalCurrencyCode":"None",
"type":"ptt",
"url":"None",
"urlNumber":"None",
"urlText":"None",
"vcardFormattedName":"None",
"vcardList":"None",
"verifiedBizName":"None",
"width":"None"
}
![image](https://user-images.githubusercontent.com/1660989/107375049-b355b080-6abe-11eb-8867-5bcd86164d7c.png)

**Comment by 3dluis** [comment]
Can solve. If someone can apply pull request for this project.

webwhatsapi/objects/message.py
factory_message method
`def factory_message(js_obj, driver):
    """Factory function for creating appropriate object given selenium JS object"""
    print(js_obj)
    if js_obj is None:
        print('Nada')
        return

    if "lat" in js_obj and "lng" in js_obj and js_obj["lat"] and js_obj["lng"]:
        return GeoMessage(js_obj, driver)

    if js_obj["isMedia"] or js_obj['type'] in ['ptt','document', 'image', 'video', 'audio', 'sticker']:
        print('isMedia')
        return MediaMessage(js_obj, driver)

    if js_obj["isNotification"]:
        print('isNotification')
        return NotificationMessage(js_obj, driver)

    if 'isMMS' in js_obj and js_obj["isMMS"]:
        print('isMMS')
        return MMSMessage(js_obj, driver)

    if js_obj["type"] in ["vcard", "multi_vcard"]:
        print('vcard')
        return VCardMessage(js_obj, driver)

    return Message(js_obj, driver)`

And class MediaMessage

`class MediaMessage(Message):
    crypt_keys = {'document': '576861747341707020446f63756d656e74204b657973',
                  'image': '576861747341707020496d616765204b657973',
                  'video': '576861747341707020566964656f204b657973',
                  'ptt': '576861747341707020417564696f204b657973',
                  'audio': '576861747341707020417564696f204b657973',
                  'sticker': '76861747341707020417564696f204b657973'}

    def __init__(self, js_obj, driver=None):
        super(MediaMessage, self).__init__(js_obj, driver)

        print(js_obj)

        self.size = self._js_obj["size"]
        self.mime = self._js_obj["mimetype"]
        if "caption" in self._js_obj:
            self.caption = self._js_obj["caption"] or ""

        self.media_key = self._js_obj.get('mediaKey')
        self.client_url = self._js_obj.get('clientUrl')
        if self.client_url is None:
            self.client_url = self._js_obj.get("deprecatedMms3Url")

        extension = mimetypes.guess_extension(self.mime or '')
        self.filename = ''.join([str(id(self)), extension or ''])

    def save_media(self, path, force_download=False):
        # gets full media
        filename = os.path.join(path, self.filename)
        ioobj = self.driver.download_media(self, force_download)
        with open(filename, "wb") as f:
            f.write(ioobj.getvalue())
        return filename

    def __repr__(self):
        return "<MediaMessage - {type} from {sender} at {timestamp} ({filename})>".format(
            type=self.type,
            sender=safe_str(self.sender.get_safe_name()),
            timestamp=self.timestamp,
            filename=self.filename
        )`

**Comment by mrodal** [comment]
Hi, I dont know what you mean, that is not this project. You can submit a PR for this project if you like
