### ISSUE TITLE
Error in function downloadFile (script timeout   (Session info: headless chrome=88.0.4324.150)). Command: return WAPI.pyFunc(()=>WAPI.downloadFile(null), arguments[0])

### ISSUE THREAD

**Issue by krypton-byte** [open-wa/wa-automate-python#64]
Error in function downloadFile (script timeout
  (Session info: headless chrome=88.0.4324.150)). Command: return WAPI.pyFunc(()=>WAPI.downloadFile(null), arguments[0])

**Comment by mrodal** [comment]
could you provide a little more information? reproduction steps?
