### ISSUE TITLE
Send voice note

### ISSUE THREAD

**Issue by Peticali** [open-wa/wa-automate-python#69]
is there an example to send voice notes? or is not possible yet?

**Comment by mrodal** [comment]
You can use `chat.send_media("path/to/audio/file")`

**Comment by Peticali** [comment]
> You can use `chat.send_media("path/to/audio/file")`

yes, it sends as audio, but what about as voice note?

**Comment by mrodal** [comment]
There you go, try with the latest version 1.3.13
`chat.send_voice_note("path/to/audio/file")`
