### ISSUE TITLE
How to avoid "Authentication timed out. Please open the app on the phone. Shutting down"

### ISSUE THREAD

**Issue by lfernandes** [open-wa/wa-automate-python#70]
Hi,

I would like to know what can I do to avoid to phone get disconnected from WhatsApp server.

Should I get display always on and WhatsApp always active on the screen?

Thanks in advance!

**Comment by mrodal** [comment]
are you sure you are using the python version? I believe you are using https://github.com/open-wa/wa-automate-nodejs/

**Comment by lfernandes** [comment]
You're right, I'll open the question there. Thanks.

**Comment by mrodal** [comment]
no problem
