### ISSUE TITLE
Add --popup in docker file

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-python#73]
To display QR code on browser, it required to run following docker command 

`docker run -e PORT=8080 -p 8080:8080 openwa/wa-automate:latest --popup`

it is better we can specify --popup in the docker file, so user need not to specify it explicitly 

Reference issue: [https://github.com/open-wa/wa-automate-nodejs/issues/1866](url)

**Comment by darkash** [comment]
I don't think the dockerfile in this repo had any line which specifies to run the app, it just stops at the installation of the lib (never tried it though)

are you perhaps posting in wrong repo? I assume you wanna post it on wa-automate-docker
CMIIW

**Comment by manojsitapara** [comment]
Ohh yes my bad !!
