### ISSUE TITLE
ReferenceError: webpackChunkbuild is not defined

### ISSUE THREAD

**Issue by 3cubos** [open-wa/wa-automate-python#74]
I have the following error message, what does this error mean? I did the update and the error continues.
Has anyone had this problem?

**Comment by mrodal** [comment]
are you using this repo or wa-automate-nodejs?

**Comment by 3cubos** [comment]
I'm using in python!

**Comment by mrodal** [comment]
can you show a screenshot of the error?

**Comment by 3cubos** [comment]
> can you show a screenshot of the error?
example: log_all.py

![image](https://user-images.githubusercontent.com/63128832/125471656-a312c460-6660-47a5-aeb6-8b94432eb4b6.png)

**Comment by mrodal** [comment]
Please try again with the latest version

**Comment by 3cubos** [comment]
> Please try again with the latest version

Thank you very much has been resolved!!!
I'm thinking about migrating from python to node.js / wa-automate-nodejs. Before my app gets more lines of code.

**Comment by mrodal** [comment]
Great! Yeah, the nodejs one is much more active also. Good luck with your project!
