### ISSUE TITLE
License Key is USD 5 per month, I wanted to know?

### ISSUE THREAD

**Issue by 3cubos** [open-wa/wa-automate-python#77]
Hello everyone, I'm already using it for some time, wa-automate-python!

the company I work for has a customer table of around 1500 records. we need to send questions (SAC) and billing notices every week (whatsapp number from records). With the license (License Key is USD 5 per month) did I allow myself to make these shipments over the course of a day?

thank you for the attention.

**Comment by mrodal** [comment]
Hello, the license allows you to send messages to numbers not in your contact list, but this is not an official (whatsapp authorizated) way of doing this, so they can ban your number if you abuse of it or if enough people mark you as spam. You can google something like "whatsapp bot ban" to find more information on that. In my personal experience, I've never had a number banned, but I think its someting you should know before using it in your company.

Also, this isn't actually an issue, this kind of discussion you can have in [our discord](https://discord.gg/dnpp72a) where probably some more people can tell you their experience

Regards!

**Comment by 3cubos** [comment]
Thanks for the answer!
My problem today is that even with the customer's contact list on the cell phone, open-wa/wa-automate-python doesn't send it. It only sends if the customer on the list has already made a previous contact.

**Comment by mrodal** [comment]
yes, sorry, I meant that, there has to be a previous conversation with that person

**Comment by 3cubos** [comment]
With this license Key is USD 5 per month, can i do this?

**Comment by mrodal** [comment]
Yes, with a license you can, but its £10 per month, or £100 a year.

You can get it from here: https://openwa.page.link/python-license

You need to get this one:
![image](https://user-images.githubusercontent.com/20667544/126712171-e0953a95-7c87-4459-a30e-e4f932cb5303.png)
