### ISSUE TITLE
Wait For Login - Stuck on Heroku

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-python#83]
Hi there
I'd like to run everything on Heroku
I've done it before
Everything on the heroku side checks out, Aptfile, Procfile, etc etc
All path are set correctly with good user profille session
gunicorn flask and socketio are working fine
running locally everything works and i log in
on heroku I get stuck on wait_for_login
(This has worked before, trying to raise the timeouts... fml)

Any help ?? thank you

**Comment by mrodal** [comment]
isnt this the same as https://github.com/open-wa/wa-automate-python/issues/82?

**Comment by fire17** [comment]
Well yes and no, but i did use @darkash suggestion and save a screenshot
I'm getting a whatsapp-web stylized page saying:
```
Browser Not Supported
we recomend using one of the following : Chrome, Firefox, Edge, Opera, Safari
```

**Comment by mrodal** [comment]
ok, lets continue on the other issue please
