### ISSUE TITLE
Open Chat returns None, and save_profile does not return wapi

### ISSUE THREAD

**Issue by riquedev** [open-wa/wa-automate-python#9]
Guys, I was doing some tests with the package and I came across these two problems:

1 - After using save_profile (modifying or removing the remove_old parameter), the code apparently does not find Wapi again, because the class returns undefined, following the Exception:

> Traceback (most recent call last):
  File "wa-automate-python/tests/__init__.py", line 21, in <module>
    print(driver.open_chat("**<valid_phone>**@c.us"))
  File "wa-automate-python\openwa\__init__.py", line 490, in open_chat
    return self.wapi_functions.openChat(chat_id)
  File "wa-automate-python\openwa\wapi_js_wrapper.py", line 43, in __getattr__
    wapi_functions = dir(self)
TypeError: 'NoneType' object is not iterable

2 - When I use open chat (expecting to open a chat with a "stranger", or someone whose I deleted all conversation (not just the messages), the function does not make any changes on the screen and returns me None. exceptions in this)

I'm using the version of the repository, I installed the whole package via git clone, and the original setup.

**Comment by darkash** [comment]
> TypeError: 'NoneType' object is not iterable

this error usually pops up when your phone isn't logged in, can you check whether it's logged in? before that line?

I never used open_chat function, but save_profile don't have problem at all, at least for me

**Comment by h98aaron** [comment]
> 2 - When I use open chat (expecting to open a chat with a "stranger", or someone whose I deleted all conversation (not just the messages), the function does not make any changes on the screen and returns me None. exceptions in this)

By that [line](https://github.com/open-wa/wa-automate-python/blob/5e7a9288e29e8f2a95e7c7b442d9f9c7359e1801/src/js/wapi.js#L2679), I guess the open_chat function is intended to open the chat panel in the browser, only if the chat already exists in the chat list.

It's not meant to start a conversation with a "stranger"

**Comment by mrodal** [comment]
We are working on that, I'll update you on that soon!

**Comment by riquedev** [comment]
> > TypeError: 'NoneType' object is not iterable
> 
> this error usually pops up when your phone isn't logged in, can you check whether it's logged in? before that line?
> 
> I never used open_chat function, but save_profile don't have problem at all, at least for me

Yes, I can login and he can perform even "check_number_status", but in fact when he returns he does not recover the session :/

Here:
```python
driver = WhatsBot(
        loadstyles=True,
        executable_path=config.get("dst_file"),
        username="test",
        profile=config.get("profile", "test"))

driver.wait_for_login(timeout=config.get("timeout", 90))
driver.save_firefox_profile()
driver.open_chat("<valid_phone>@c.us")
```



> > 2 - When I use open chat (expecting to open a chat with a "stranger", or someone whose I deleted all conversation (not just the messages), the function does not make any changes on the screen and returns me None. exceptions in this)
> 
> By that [line](https://github.com/open-wa/wa-automate-python/blob/5e7a9288e29e8f2a95e7c7b442d9f9c7359e1801/src/js/wapi.js#L2679), I guess the open_chat function is intended to open the chat panel in the browser, only if the chat already exists in the chat list.
> 
> It's not meant to start a conversation with a "stranger"


Ahh, I understand x_x
Is that in my use case I would need to be the first to send the message.



> We are working on that, I'll update you on that soon!

Thanks!!

**Comment by darkash** [comment]
> > > TypeError: 'NoneType' object is not iterable
> > 
> > 
> > this error usually pops up when your phone isn't logged in, can you check whether it's logged in? before that line?
> > I never used open_chat function, but save_profile don't have problem at all, at least for me
> 
> Yes, I can login and he can perform even "check_number_status", but in fact when he returns he does not recover the session :/
> 
> Here:
> 
> ```python
> driver = WhatsBot(
>         loadstyles=True,
>         executable_path=config.get("dst_file"),
>         username="test",
>         profile=config.get("profile", "test"))
> 
> driver.wait_for_login(timeout=config.get("timeout", 90))
> driver.save_firefox_profile()
> driver.open_chat("<valid_phone>@c.us")
> ```
> 
> > > 2 - When I use open chat (expecting to open a chat with a "stranger", or someone whose I deleted all conversation (not just the messages), the function does not make any changes on the screen and returns me None. exceptions in this)
> > 
> > 
> > By that [line](https://github.com/open-wa/wa-automate-python/blob/5e7a9288e29e8f2a95e7c7b442d9f9c7359e1801/src/js/wapi.js#L2679), I guess the open_chat function is intended to open the chat panel in the browser, only if the chat already exists in the chat list.
> > It's not meant to start a conversation with a "stranger"
> 
> Ahh, I understand x_x
> Is that in my use case I would need to be the first to send the message.
> 
> > We are working on that, I'll update you on that soon!
> 
> Thanks!!

I think you can do something like this, it's a workaround but works for me
```
try:
    driver.get_chat_by_id('<valid_number>@c.us')
    driver.chat_send_message('<valid_number>@c.us', 'message')
except ChatNotFoundError:
    driver.wapi_functions.sendMessageToID('<valid_number>@c.us', 'message')
```
The caveat is the except block does not return Message object, instead it always return bool

**Comment by mrodal** [comment]
Hey, good news, with the latest version (1.1.1) now you can contact unknown number, using a [license key](https://github.com/open-wa/wa-automate-python#license-key) and providing your use case. This helps prevent bad uses like spamming, and also is some help for us maintainers for the hours we put in.

Check out https://github.com/open-wa/wa-automate-python#license-key for instructions on how to get a key
