### ISSUE TITLE
check_number_status not working, always return 400

### ISSUE THREAD

**Issue by hh23485** [open-wa/wa-automate-python#93]
> - Advertising of monetized Frameworks is strictly forbidden and will be reported 
> - [x] The language must be English, if you are not fluent in English consider using: https://www.deepl.com/translator if it supports your native language
> 
> - [x] Please check if any other issue already adresses your concerns or if a recent PR is already fixing the mentioned issue
> 
> - [x] Please make sure to **format your code**, and to mark your code as such, with the provided tools from github (upper right of this box)
> 
> - [x] Please state your **Operating System (inlcuding version)**, your **Python Version**, and your **installation way (pip, from repo)** and if you are running it inside a docker container
> 
> - [x] Note that the pip installation might be behind, so try to fix your issue with a pull from the repo and update to the most recent version
> 
> - [x] Follow the Stackoverflow Guidelines (https://stackoverflow.com/help/how-to-ask) when in need of help
>
> - [x] Consider posting your question on Stackoverflow if it is a general programming question
> 
> - [x] There will be no support for spamming, or other mischief 
> 
>- [x] There will be no support for finding professionals

I found the check_number_status api always return 400. But no documents tell what's this means?

The code to call the api
```
from openwa import WhatsAPIDriver, NumberStatus

# from webwhatsapi import WhatsAPIDriver

driver = WhatsAPIDriver()
driver.get_qr()
driver.wait_for_login()
time.sleep(5)
status: NumberStatus = driver.check_number_status('86186********12')
print(status)
```

Python version: 3.7
Installed from: pip latest
openwa version: '1.3.15'

**Comment by mrodal** [comment]
Im getting the correct response, please try again. It could be a issue with the underlying wa-automate-nodejs that has been fixed
![image](https://user-images.githubusercontent.com/20667544/143247048-58c4ee38-27ef-4854-91f8-87babbb85e6b.png)
